apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  labels:
    component: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-1
    fsType: ext4