apiVersion: v1
kind: Service
metadata:
  labels:
    service: ghost
  name: ghost
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 2368
    protocol: TCP
    targetPort: 2368
  selector:
    service: ghost
