apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: ghost
  name: ghost
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  replicas: 10
  selector:
    matchLabels:
      service: ghost
  template:
    metadata:
      labels:
        service: ghost
    spec:
      containers:
      - name: ghost
        image: scheele/my-ghost:1.0
        env:
        - name: CLOUDINARY_URL
          valueFrom:
            secretKeyRef:
              name: ghost-secret
              key: cloudinary-url
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ghost-config
              key: node-env
        - name: GHOST_URL
          valueFrom:
            configMapKeyRef:
              name: ghost-config
              key: ghost-url
        ports:
        - containerPort: 2368
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
      restartPolicy: Always
