apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    component: mysql
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/local-pv-1
