apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
#  annotations:
#    volume.alpha.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      component: mysql